name: Link Check
on:
  push:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose --no-progress --accept 200,204,301,302,307,308 .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
